### ISSUE TITLE
Tz-Clock, conky, plank, cairo-dock

### ISSUE THREAD

**Issue by constantius24** [mocaccinoOS/community-repository#21]
hello. I ask community to build these packages... best regards

**Comment by msdobrescu** [comment]
Conky, plank, cairo-dock were added.
Could not compile Tz-Clock yet using Gentoo's tools current versions, it seems outdated and its developer did not respond yet.

**Comment by msdobrescu** [comment]
Those depend on old code and volatile overlays.
