### ISSUE TITLE
Gnu Octave

### ISSUE THREAD

**Issue by VolvoBirkenstock** [mocaccinoOS/community-repository#29]
I am unable to find gnu octave in the mocaccino repositories.  
If it is already available in mocaccino, please tell me where it is.  
If it is not available, please consider building it and releasing it. 
Gnu Octave is the open source equivalent of Matlab.  
Thank you for your consideration of this request.

**Comment by msdobrescu** [comment]
@VolvoBirkenstock, I've added Octave.
I am have no experience with it, would you please test it and provide a feed-back if it works or not, pelase?

**Comment by VolvoBirkenstock** [comment]
@msdobrescu, 
I've started the installation of Octave in my VM.  It's taking a long time.  I should have increased the capabilities of the VM prior to starting the install process.  I will let it run overnight and hope to provide you feedback "soon".

**Comment by msdobrescu** [comment]
@VolvoBirkenstock, thanks! It is a huge package indeed, a true development environment by itself. I tried to add all that was available for it in the Gentoo repos. If you have some hints of what is not needed at all and should be dropped, please specify!

**Comment by VolvoBirkenstock** [comment]
I've tested image generation, produced/displayed multiple images and line plots and it looks good.  I haven't used the Fourier transform functionality yet.  

Frankly, there is too much functionality to correctly test without automating a very large test suite.  Why?  Because Octave effectively is Open Source Matlab.  Octave and Matlab are used by researchers, scientific programmers, students and much more.  You can use it for neural networks, machine/artificial intelligence, statistical pattern recognition, audio/signal/image processing, computer vision, graphics, meteorology, applied mathematics, differential and integral equations, etcetera, but mostly for modelling algorithms.  A PhD student could do their thesis research with it.  It is extremely fungible.  It's definitely not for real time, but you can use it to dramatically improve algorithm efficiency before transferring the algorithm onto serious hardware, such as a GPU or similar.  Since it supports a huge spectrum of different technologies, it will have MANY supporting software libraries.  There is no way around that.  The more you include, the better it supports _all_ users. 

Thank you VERY much, @msdobrescu !!!

**Comment by msdobrescu** [comment]
Well, we don't test it per se, as its developers, just check that works with regard to our build and some real use scenario.
Thank you for confirming, @VolvoBirkenstock!
