### ISSUE TITLE
bc/dc package request

### ISSUE THREAD

**Issue by VolvoBirkenstock** [mocaccinoOS/community-repository#31]
I have multiple shellscripts that are dependent on using the "dc" executable.  

In Gentoo, at https://www.portagefilelist.de/site/query/file/, I can place a query for "dc". After clicking the "search" button, I can look for a result that contains "/usr/bin/dc", and I find it in the "sys-devel/bc" package.  

I have not been able to find a package containing either "bc" or "dc" in your stable repositories.  Can you either tell me how to specify this package with a luet command or provide this application package?  

Thank you very much in advance.

**Comment by msdobrescu** [comment]
Hello, right now I do not recommend updating, as it takes place a big migration to new versions and octave is not yet rebuilt. Also some things may break too.

Concerning the `sys-devel/bc` package, it is already is layers/X.

**Comment by VolvoBirkenstock** [comment]
Hello, @msdobrescu .
Could you let me know when it is "safe" to upgrade? 
Thank you very much!

**Comment by msdobrescu** [comment]
Hello, we've synced the repos, you can proceed, but may get some conflicts that usually occur when atoms were moved between packages. You should uninstall the packages dependent on those if that happen and re-install them. Settings should not be lost.
