### ISSUE TITLE
Megasync

### ISSUE THREAD

**Issue by wvpianoman** [mocaccinoOS/community-repository#35]
Shows available in Gentoo here

http://gpo.zugaina.org/net-misc/megasync

Would this be possible to add to this pkg?

**Comment by msdobrescu** [comment]
Added. Please test it!

**Comment by wvpianoman** [comment]
Works perfectly

**Comment by wvpianoman** [comment]
Thank you very much

**Comment by msdobrescu** [comment]
Don't mention it!
All good? Can we close this ticket?
