### ISSUE TITLE
package request: rclone-browser

### ISSUE THREAD

**Issue by wvpianoman** [mocaccinoOS/community-repository#36]
This isn't in gentoo, but it sure makes using rclone a lot easier

https://kapitainsky.github.io/RcloneBrowser/  Is the webpage. 

When you get a chance.

**Comment by msdobrescu** [comment]
This one http://gpo.zugaina.org/net-misc/RcloneBrowser ?

**Comment by msdobrescu** [comment]
Added, please check!

**Comment by wvpianoman** [comment]
It works.  100%.   Thank you SO much!!!!!

**Comment by msdobrescu** [comment]
Sure, no problem!
