### ISSUE TITLE
easyeffects

### ISSUE THREAD

**Issue by 01fiore** [mocaccinoOS/community-repository#38]
I ask for the integration in Moccacinno of the software Easyeffects. 

Thanks in advance.

**Comment by msdobrescu** [comment]
Hello, I've added, upgrade repos and try `luet install apps/easyeffects`.

**Comment by 01fiore** [comment]
Thank you very much my friend, Easyeffects work perfectly.
![Easyeffects](https://github.com/user-attachments/assets/997fd2aa-6a8a-49b9-961a-0d28e8346b75)

**Comment by msdobrescu** [comment]
Souds great ;)
